### ISSUE TITLE
Unable to get plugin to work with neo4j 3.0.4

### ISSUE THREAD

**Issue by sidwagle** [thinkaurelius/neo4j-gremlin-plugin#19]
Neo4j version = 3.0.4
JDK version = 1.8.0_60

I have compiled the plugin with 3.0.4 version of neo4j and with jdk8.

Enabled the plugin using the new 3.X config:
dbms.unmanaged_extension_classes=com.thinkaurelius.neo4j.plugins=/tp

2016-08-30 19:11:53.368+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-75bf9223@410a4290==org.neo4j.server.web.NeoServletContainer,-1,false Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-75bf9223@410a4290==org.neo4j.server.web.NeoServletContainer,-1,false
org.neo4j.server.ServerStartupException: Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-75bf9223@410a4290==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-75bf9223@410a4290==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:353)
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:168)
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:316)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:208)
        ... 3 more
Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
        at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
        at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
        ... 22 more

**Comment by mihairaulea** [comment]
Not involved in the project in any way, but here is what the project wiki says: "The Neo4j Gremlin Plugin provides the ability to query/traverse a Neo4j graph using Gremlin via Neo4j Server 2.x."
